version: '3.8'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=nodejs_user
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nodejs_app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: nodejs_user
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: nodejs_app
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

